export const ADD_PERSON = "ADD_PERSON";
export const DELETE_PERSON = "DELETE_PERSON";
export const FETCH_PERSON = "FETCH_PERSON";
export const FETCH_PERSONS = "FETCH_PERSONS";
export const EDIT_PERSON = "EDIT_PERSON";
export const FETCH_PERSON_FIELDS = "FETCH_PERSON_FIELDS";
export const REORDER_LIST = "REORDER_LIST";
